name: CI Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Enable pnpm via corepack
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm exec turbo run build

      - name: Lint
        run: pnpm exec turbo run lint

      - name: Test
        run: pnpm exec turbo run test

      - name: Spellcheck
        run: pnpm exec turbo run spellcheck
